### ISSUE TITLE
Multiple closing shortcodes in content causes stack.pop exception

### ISSUE THREAD

**Issue by deanmarcussen** [sebastienros/shortcodes#2]
When multiple closing shortcodes are contained in the same piece of content there is a stack.pop exception

Change this test to 
```
        [Theory]
        [InlineData("[hello]a[/hello] [hello]a[/hello]", "Hello world! Hello world!")]
        public async Task ProcessClosingShortcodes(string input, string expected)
        {
            var parser = new ShortcodesProcessor(_provider);

            Assert.Equal(expected, await parser.EvaluateAsync(input));
        }
```

and there is this exception `System.InvalidOperationException : Stack empty.`

**Comment by sebastienros** [comment]
Snap, I think my folding logic is wrong, as I assume it's actually taking the outer tags into account ;)
Looking into it.

**Comment by sebastienros** [comment]
I fixed the stackoverflow but my previous comment is a different issue I am working on.
It sees `[a]foo[/a] [a]bar[/a]` as `[a] CONTENT [/a]` where content is `foo[/a] [a]bar` 
Because the folding is done from the outer bounds.
