### ISSUE TITLE
Consider context object

### ISSUE THREAD

**Issue by deanmarcussen** [sebastienros/shortcodes#7]
It might be useful to have be able to pass a context object to the processor.

Use case here https://github.com/OrchardCMS/OrchardCore/issues/6199#issuecomment-652989113

Probably just an object might give issues when wanting to cast it/access it in liquid though, so it might need to be more of an accessor like `Arguments`

**Comment by sebastienros** [comment]
I am thinking about using Dictionary. Then when executing the template shortcodes we can pass custom values.

**Comment by deanmarcussen** [comment]
Custom Dictionary sounds good

Currently for args I have
```
            TemplateContext.GlobalMemberAccessStrategy.Register<Arguments, object>((obj, name) => obj.NamedOrDefault(name));

            // Prevent Arguments from being converted to an ArrayValue as they implement IEnumerable
            FluidValue.SetTypeMapping<Arguments>(o => new ObjectValue(o));
```

**Comment by sebastienros** [comment]
I have no idea what you are doing here ;) 
Or are you telling me that having another "Arguments" typed context variable would be better than a "Dictionary".

**Comment by sebastienros** [comment]
Nah, `Arguments` is not good here. Notion of "default" or numbered properties doesn't make sense.

**Comment by deanmarcussen** [comment]
Haha sorry, I am explaining badly, and totally out of context, no pun intended.

But you just put a pr in looks ideal
